In [2]:
#Computacao Numerica - Calculo Numerico
#Algoritmo 1.1 - Eliminacao de Gauss

import numpy as np

In [3]:
def matrix_scaling(matrix_components, matrix_result):
    
    # size matrix result.
    tam = len(matrix_result)

    for i in range(tam-1):
        for j in range(i+1,tam):
            if matrix_components[j,i] != 0:
                m = matrix_components[j,i]/matrix_components[i,i]
                matrix_components[j] = matrix_components[j] - (m*matrix_components[i])
                matrix_result[j] =  matrix_result[j] - (m*matrix_result[i])
    
    return (matrix_components, matrix_result)
            

In [4]:
def gaus_elim(matrix_components, matrix_result):

    # size matrix result.
    n = len(matrix_result)

    # Back substitution
    for k in range(n-1, -1, -1):
        matrix_result[k] = (matrix_result[k] - np.dot(matrix_components[k, k+1:n], matrix_result[k+1:n]))/matrix_components[k, k]
    return (matrix_components,matrix_result)

In [5]:
z = np.array([[4.0, 1.0, 2.0], [2.0, 4.0, -1.0], [1.0, 1.0, -3.0]])
k = np.array([[9.0, -5.0, -9.0]])

In [6]:
print(k[0])

[ 9. -5. -9.]


In [7]:
print(z)

[[ 4.  1.  2.]
 [ 2.  4. -1.]
 [ 1.  1. -3.]]


In [8]:
(matrix_components, matrix_result) = matrix_scaling(z,k[0])

print(matrix_components)

[[ 4.          1.          2.        ]
 [ 0.          3.5        -2.        ]
 [ 0.          0.         -3.07142857]]


In [9]:
print(matrix_result)

[ 9.         -9.5        -9.21428571]


In [10]:
(matrix_components, matrix_result) = gaus_elim(matrix_components,matrix_result)

print(matrix_components)
print(matrix_result)

[[ 4.          1.          2.        ]
 [ 0.          3.5        -2.        ]
 [ 0.          0.         -3.07142857]]
[ 1. -1.  3.]


In [20]:
matrix_components = np.array([[1.0,(1/2),(1/3),(1/4)], [(1/2),(1/3),(1/4),(1/5)], [(1/3),(1/4),(1/5),(1/6)],[(1/4),(1/5),(1/6),(1/7)]])
matrix_result = np.array([[(1/6), (1/7), (1/8),(1/9)]])


print("LETRA A - Matriz Inicial")
print(matrix_components)

print("Matriz Resultaos")
print(matrix_result)

(matrix_components, matrix_result) = matrix_scaling(matrix_components,matrix_result[0])
(matrix_components, matrix_result) = gaus_elim(matrix_components,matrix_result)

LETRA A - Matriz Inicial
[[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
Matriz Resultaos
[[0.16666667 0.14285714 0.125      0.11111111]]


In [15]:

print("Matriz final")
print(matrix_components)
print("Resultados")
print(matrix_result)

Matriz final
[[ 1.00000000e+00  5.00000000e-01  3.33333333e-01  2.50000000e-01]
 [ 0.00000000e+00  8.33333333e-02  8.33333333e-02  7.50000000e-02]
 [ 0.00000000e+00 -1.38777878e-17  5.55555556e-03  8.33333333e-03]
 [ 0.00000000e+00  2.08166817e-17  0.00000000e+00  3.57142857e-04]]
Resultados
[-0.03174603  0.5952381  -2.38095238  2.77777778]


In [21]:
matrix_components = np.array([
    [ 2.0,1.0,-1.0,4.0,-3.0], 
    [1.0,0.0,2.0,-1.0,1.0],
    [0.0,-2.0,-1.0,1.0,-1.0],
    [3.0,1.0,-4.0,0.0,5.0],
    [1.0,-1.0,-1.0,-1.0,1.0]
 ])
matrix_result = np.array([[7.0,2.0,-5.0,6.0,3.0]])


print("LETRA B - Matriz Inicial")
print(matrix_components)
print("Matriz Resultaos")
print(matrix_result)

(matrix_components, matrix_result) = matrix_scaling(matrix_components,matrix_result[0])
(matrix_components, matrix_result) = gaus_elim(matrix_components,matrix_result)

LETRA B - Matriz Inicial
[[ 2.  1. -1.  4. -3.]
 [ 1.  0.  2. -1.  1.]
 [ 0. -2. -1.  1. -1.]
 [ 3.  1. -4.  0.  5.]
 [ 1. -1. -1. -1.  1.]]
Matriz Resultaos
[[ 7.  2. -5.  6.  3.]]


In [18]:
print("Matriz final")
print(matrix_components)
print("Resultados")
print(matrix_result)

Matriz final
[[ 2.00000000e+00  1.00000000e+00 -1.00000000e+00  4.00000000e+00
  -3.00000000e+00]
 [ 0.00000000e+00 -5.00000000e-01  2.50000000e+00 -3.00000000e+00
   2.50000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.10000000e+01  1.30000000e+01
  -1.10000000e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -8.90909091e+00
   1.20000000e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -4.44089210e-16
  -1.65306122e+00]]
Resultados
[ 3.98765432  2.85185185 -1.28395062 -3.37037037 -2.79012346]
